import { Product } from './types';

export const products: Product[] = [
  {
    id: 1,
    name: 'Oversized Wool Coat',
    category: 'Men',
    price: 720.00,
    fabric: '100% Virgin Wool',
    details: 'A signature oversized coat crafted from double-faced virgin wool. Unlined for a lighter feel, perfect for layering.',
    images: [
      "https://picsum.photos/seed/product1_1/800/1200",
      "https://picsum.photos/seed/product1_2/800/1200",
      "https://picsum.photos/seed/product1_3/800/1200"
    ],
    availableSizes: ['M', 'L', 'XL'],
    color: 'Black',
  },
  {
    id: 2,
    name: 'Cashmere Blend Hoodie',
    category: 'Essentials',
    price: 350.00,
    fabric: '85% Cotton, 15% Cashmere',
    details: 'The pinnacle of comfort. A relaxed-fit hoodie in an ultra-soft cashmere and cotton blend. Minimalist branding.',
    images: [
      "https://picsum.photos/seed/product2_1/800/1200",
      "https://picsum.photos/seed/product2_2/800/1200",
      "https://picsum.photos/seed/product2_3/800/1200"
    ],
    availableSizes: ['S', 'M', 'L'],
    color: 'Beige',
  },
  {
    id: 3,
    name: 'Silk Draped Blouse',
    category: 'Women',
    price: 480.00,
    fabric: '100% Mulberry Silk',
    details: 'An fluid, elegant blouse cut from pure Mulberry silk. Features a concealed placket and draped neckline.',
    images: [
      "https://picsum.photos/seed/product3_1/800/1200",
      "https://picsum.photos/seed/product3_2/800/1200",
    ],
    availableSizes: ['S', 'M'],
    color: 'White',
  },
  {
    id: 4,
    name: 'Modern Tailored Trousers',
    category: 'Men',
    price: 290.00,
    fabric: '60% Wool, 38% Polyester, 2% Elastane',
    details: 'A modern cut trouser with a slight taper. The wool-blend fabric provides structure and comfort. Single front pleat.',
    images: [
      "https://picsum.photos/seed/product4_1/800/1200",
      "https://picsum.photos/seed/product4_2/800/1200",
    ],
    availableSizes: ['S', 'M', 'L'],
    color: 'Black',
  },
  {
    id: 5,
    name: 'The Essential Tee',
    category: 'Essentials',
    price: 95.00,
    fabric: '100% Pima Cotton',
    details: 'A heavyweight, boxy-fit t-shirt made from premium Pima cotton. Features a high-ribbed collar.',
    images: [
      "https://picsum.photos/seed/product5_1/800/1200",
      "https://picsum.photos/seed/product5_2/800/1200",
    ],
    availableSizes: ['S', 'M', 'L', 'XL'],
    color: 'White',
  },
  {
    id: 6,
    name: 'Crepe Modest Gown',
    category: 'Abaya',
    price: 610.00,
    fabric: '100% Japanese Crepe',
    details: 'An elegant, flowing gown cut from premium Japanese crepe. Full-length with a matching sheila. Designed for a graceful, modest silhouette.',
    images: [
      "https://picsum.photos/seed/product6_1/800/1200",
      "https://picsum.photos/seed/product6_2/800/1200",
    ],
    availableSizes: ['M', 'L'],
    color: 'Black',
  },
  {
    id: 7,
    name: 'Signature Knit Polo',
    category: 'Men',
    price: 310.00,
    fabric: '70% Cotton, 30% Silk',
    details: 'A refined knit polo with a modern fit, crafted from a luxurious cotton-silk blend.',
    images: [
      "https://picsum.photos/seed/product7_1/800/1200",
      "https://picsum.photos/seed/product7_2/800/1200",
      "https://picsum.photos/seed/product7_3/800/1200",
    ],
    availableSizes: ['S', 'M', 'L'],
    color: 'Beige',
  },
  {
    id: 8,
    name: 'Junior Essential Hoodie',
    category: 'Children',
    price: 150.00,
    fabric: '100% Organic Cotton',
    details: 'A soft, organic cotton hoodie for children, designed for comfort and durability.',
    images: [
      "https://picsum.photos/seed/product8_1/800/1200",
      "https://picsum.photos/seed/product8_2/800/1200",
    ],
    availableSizes: ['S', 'M', 'L'],
    color: 'Beige',
  },
];

export const countries: string[] = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan",
  "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi",
  "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo, Democratic Republic of the", "Congo, Republic of the", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czech Republic",
  "Denmark", "Djibouti", "Dominica", "Dominican Republic",
  "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia",
  "Fiji", "Finland", "France",
  "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
  "Haiti", "Honduras", "Hungary",
  "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy",
  "Jamaica", "Japan", "Jordan",
  "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait", "Kyrgyzstan",
  "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg",
  "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar (Burma)",
  "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway",
  "Oman",
  "Pakistan", "Palau", "Palestine State", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal",
  "Qatar",
  "Romania", "Russia", "Rwanda",
  "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria",
  "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
  "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States of America", "Uruguay", "Uzbekistan",
  "Vanuatu", "Vatican City", "Venezuela", "Vietnam",
  "Yemen",
  "Zambia", "Zimbabwe"
];